export { default as Heading } from './heading';
export { default as Large } from './large';
export { default as LinkText } from './link';
export { default as Logo } from './logo';
export { default as Paragraph } from './paragraph';
export { default as Small } from './small';
export { default as Subheading } from './subheading';
export { default as Subtitle } from './subtitle';
export { default as Title } from './title';
